### ISSUE TITLE
Test run the Caribbean model including RIVERS (write instructions here)

### ISSUE THREAD

**Issue by ocgabs** [ocgabs/Caribbean#21]

**Comment by vleguenn** [comment]
- First you need to turn rivers on. 

vi namelist_cfg
...
ln_rnf      = .true.   !  Runoffs                                   (T => fill namsbc_rnf) ! val: turn to true to activate rivers


- Then you need to include the river section (namsbc_rnf), can be put below the namtra_qsr section:

vi namelist_cfg
...
!-----------------------------------------------------------------------
&namsbc_rnf    !   runoffs namelist surface boundary condition          (ln_rnf=T)
!-----------------------------------------------------------------------
!              !  file name           ! frequency (hours) ! variable  ! time interp. !  clim  ! 'yearly'/ ! weights  ! rotation ! land/sea mask !
!              !                      !  (if <0  months)  !   name    !   (logical)  !  (T/F) ! 'monthly' ! filename ! pairing  ! filename      !
   sn_rnf      = 'rivers_NOSPREAD',        24         , 'rorunoff',   .true.     , .false. , 'yearly'  , ''       , ''       , ''
   sn_cnf      = 'rivers_NOSPREAD',         0         , 'socoefr',   .false.    , .true. , 'yearly'  , ''       , ''       , ''
   sn_dep_rnf  = 'rivers_NOSPREAD',        24         , 'DEPTHrunoff' ,   .false.    , .false. , 'yearly'  , ''       , ''       , ''
   cn_dir      = './RIVERS/'      !  root directory for the location of the runoff files
   ln_rnf_mouth= .false.    !  specific treatment at rivers mouths
      rn_hrnf     =  15.e0    !  depth over which enhanced vertical mixing is used    (ln_rnf_mouth=T)
      rn_avt_rnf  =   1.e-3   !  value of the additional vertical mixing coef. [m2/s] (ln_rnf_mouth=T)
   rn_rfact    =   1.e0    !  multiplicative factor for runoff
   ln_rnf_depth= .true.   !  read in depth information for runoff
   ln_rnf_tem  = .false.   !  read in temperature information for runoff
   ln_rnf_sal  = .false.   !  read in salinity information for runoff
   ln_rnf_depth_ini = .false. ! compute depth at initialisation from runoff file
      rn_rnf_max  = 0.3 ! 5.735e-4  !  max value of the runoff climatologie over global domain ( ln_rnf_depth_ini = .true )
      rn_dep_max  = 10.      !  depth over which runoffs is spread ( ln_rnf_depth_ini = .true )
      nn_rnf_depth_file = 0   !  create (=1) a runoff depth file or not (=0)
/


Note : the climatology is put to false (Anna had issues using it true when using daily values). I think it's more coherent to set it to false as we are not using a climatology. The above namelist also uses depth values (ln_rnf_depth=true), maybe this can be turned off, but it seems to run ok when they are taken into account. 

I made a try run  (2009) with rivers ON, it runs OK. But this was using river files NOT SPREAD.

**Comment by vleguenn** [comment]
**Temperature (Sept, 2009) : NO RIVERS**
![Sept_Temp_NO_rivers](https://user-images.githubusercontent.com/30412310/107763375-d9818780-6d2e-11eb-9753-bea644c50818.png)
![Sept_Temp_NO_rivers_colorbar](https://user-images.githubusercontent.com/30412310/107764111-ece12280-6d2f-11eb-8271-3c417901af52.png)


**Salinity (Sept, 2009) : NO RIVERS**
![Sept_Salinity_NO_rivers](https://user-images.githubusercontent.com/30412310/107763415-e56d4980-6d2e-11eb-9ab6-1a2619ecfec4.png)
![Sept_Salinity_NO_rivers_colorbar](https://user-images.githubusercontent.com/30412310/107764134-f4a0c700-6d2f-11eb-9648-1c9d810e0b08.png)

**Temperature (Sept, 2009) : WITH RIVERS (not spread)**
![Sept_Temp_Rivers_NOT_spread](https://user-images.githubusercontent.com/30412310/107763464-f61dbf80-6d2e-11eb-96bb-1a0fe4a76ae4.png)
![Sept_Temp_Rivers_NOT_spread_colorbar](https://user-images.githubusercontent.com/30412310/107764144-f9fe1180-6d2f-11eb-9914-97bd93e3f087.png)

**Salinity (Sept, 2009) : WITH RIVERS (not spread)**
![Sept_Salinity_Rivers_NOT_spread](https://user-images.githubusercontent.com/30412310/107763501-06359f00-6d2f-11eb-898a-0502ae9f6a3e.png)
![Sept_Salinity_Rivers_NOT_spread_colorbar](https://user-images.githubusercontent.com/30412310/107764151-fe2a2f00-6d2f-11eb-8f8b-fe43c2c1a0c2.png)


There is a decrease of temperature around the river mouths and a decrease in salinity (freshwater inputs).

**Comment by vleguenn** [comment]
I update the `CME` folder to include the script I used to compare NEMO outputs with SATELLITE data for SST. (go here : _/projectsa/CME/3DCaribbeanNEMO/RIVERS/NEMO_VS_SAT_). The satellite data are here : _/projectsa/CME/3DCaribbeanNEMO/RIVERS/AQUA_MODIS_DATA_

The results of the runs with rivers (not spread) were then compared with satellite sst for the spin-up year (2009): 

![AQUA_MODIS_minus_NEMO_SST_rivers_not_spread_Jan_to_June_2009](https://user-images.githubusercontent.com/30412310/108341757-4cc94480-71da-11eb-9033-35d9bbe7df37.png)

![AQUA_MODIS_minus_NEMO_SST_rivers_not_spread_July_to_Dec_2009](https://user-images.githubusercontent.com/30412310/108341767-4fc43500-71da-11eb-84f3-91faf143c43a.png)

**Comment by mpayopayo** [comment]
Comparison of runs spread rivers and non-spread rivers and MODIS satellite data for spin-up year 2009:
![image](https://user-images.githubusercontent.com/77632182/110115406-f2211280-7dad-11eb-9ed1-cd96dfa451c3.png)

Largest differences at river mouths (as expected) and spread rivers run compares best to MODIS. 
Run for spin up year OK, run for 2010 OK. Run for 2011 blows  up. Fig are location of the tile where it blows up and tile where it blows up (ssh>20m)
![image](https://user-images.githubusercontent.com/77632182/110115644-4a581480-7dae-11eb-82ab-3e647d833df6.png)
![image](https://user-images.githubusercontent.com/77632182/110115675-5512a980-7dae-11eb-8404-67a7b42cc7e6.png)

Strategies to sort that 1) spreading over more cells the river discharge and 2) reducing the time step.

1) By spreading the river discharge it blows up two time steps later and the same point

2) With the reduced time step I have not managed to restart it yet. It doesn't recognize the time step it is at and looks for a ___1 river file instead of 2011 since it refers to the number of timesteps since the beginning of the simulation. Forcing it to read from the namelist doesn't work either

Other alternatives: a) cap river discharge, b) modify bathymetry since blow up close to a bay might induce resonance c) start simulations from 2009 with a smaller timestep since the model wants the same timestep for the whole simulation. All of them imply trial and error and are time consuming within the timeframe we have.
