### ISSUE TITLE
Get PyNEMO working to generate forcing files from 2010 to the present (ideally).

### ISSUE THREAD

**Issue by ocgabs** [ocgabs/Caribbean#7]

**Comment by vleguenn** [comment]
The method used to generate 3D boundaries works well using Pynemo on Livljobs7. The parent dataset used is GLOBAL_REANALYSIS_PHY_001_030-TDS (global-reanalysis-phy-001-030-daily) and were downloaded through the Motu web client. By using Copernicus datasets instead of the usual ORCA as parent datasets, we can generate lateral boundaries for a greater time period (only until 2015 with ORCA whereas we can go up to 2019 with Copernicus). Moreover, there was apparently 2 years prior 2015 that have a different setup/variables names in ORCA. So Copernicus seems better in those regards.

**Comment by vleguenn** [comment]
As soon as the parent data are downloaded, I am generating the 3D lateral boundaries associated to the year. This is continuously runing as background on Livljobs7, so all the years of interest should be finished generating in the coming 3 days. I will re-open this card if ever I encounter any issues along the way, but otherwise, this can be close now.
